name: Review Pull Request

on:
    workflow_run:
      workflows: [Continuous Integration]
      types:
        - requested
        - completed

permissions:
    pull-requests: write

jobs:
    requested:
        runs-on: ubuntu-latest
        if: github.event.action == 'requested'
        steps:
            - name: "Emit workflow event"
              env:
                GITHUB_CONTEXT: ${{ toJson(github.event) }}
              run: |
                echo "$GITHUB_CONTEXT"
            # - uses: mondeja/remove-labels-gh-action@v2
            #   with:
            #     token: ${{ secrets.GITHUB_TOKEN }}
            #     labels: needs-work

    completed:
        runs-on: ubuntu-latest
        if: github.event.action == 'completed'
        steps:
            - name: "Emit workflow event"
              env:
                GITHUB_CONTEXT: ${{ toJson(github.event) }}
              run: |
                echo "$GITHUB_CONTEXT"
        #   - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        #     env:
        #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #       GH_REPO: ${{ github.repository }}
        #       NUMBER: ${{ github.event.pull_request.number }}
        #       LABELS: needs-work
